version: '3'
services:
  api:
    restart: unless-stopped
    image: yat-partner:latest
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
#      - YAT_CODE_IDS=
#      - YAT_SECRETS=
#      - YAT_API_URL=https://a.y.at
#      - YAT_API_KEY=
    env_file:
      - .env
